// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnaLnxtjInK3Oth7uNnrcTmMcgr7gRDhU',
    appId: '1:127511417253:web:17c70504d5eb819f0f184c',
    messagingSenderId: '127511417253',
    projectId: 'chatbot-f5c8e',
    authDomain: 'chatbot-f5c8e.firebaseapp.com',
    storageBucket: 'chatbot-f5c8e.firebasestorage.app',
    measurementId: 'G-FQVNQ9DEBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJxWOq_8ckJTPOrbQyYBS_qNIbVuVKCoI',
    appId: '1:127511417253:android:70be4136913125750f184c',
    messagingSenderId: '127511417253',
    projectId: 'chatbot-f5c8e',
    storageBucket: 'chatbot-f5c8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshw630Qy8DEpEoikuhIhDD8dmakWcWbs',
    appId: '1:127511417253:ios:5c2885c756cd9b890f184c',
    messagingSenderId: '127511417253',
    projectId: 'chatbot-f5c8e',
    storageBucket: 'chatbot-f5c8e.firebasestorage.app',
    iosClientId: '127511417253-i9s7h4abvvm43eatu4q31urv84bb2jld.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}
